spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_db?createDatabaseIfNotExist=true
    username: root
    password: Petya159753!

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true






